[general]
import = [
    "./themes/monokai_pro.toml"
]
live_config_reload = true


[window]
dimensions.columns = 100
dimensions.lines = 30
option_as_alt = "Both"

[font]
normal.family = "CaskaydiaCove NF"
normal.style = "Regular"

[cursor]
style.shape="Block"

[terminal]
osc52="CopyPaste"
