[general]
import = [
    "./themes/rose-pine.toml"
]
live_config_reload = true


[window]
dimensions.columns = 100
dimensions.lines = 30
option_as_alt = "Both"

[font]
size=13
normal.family = "Hack Nerd Font"
normal.style = "Regular"

[cursor]
style.shape="Block"

[terminal]
osc52="CopyPaste"
